/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_GT_GT = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  anon_sym_COLON = 5,
  anon_sym_raw = 6,
  anon_sym_str = 7,
  anon_sym_i8 = 8,
  anon_sym_i16 = 9,
  anon_sym_i32 = 10,
  anon_sym_i64 = 11,
  anon_sym_u8 = 12,
  anon_sym_u16 = 13,
  anon_sym_u32 = 14,
  anon_sym_u64 = 15,
  anon_sym_f16 = 16,
  anon_sym_f32 = 17,
  anon_sym_f64 = 18,
  anon_sym_LBRACK_RBRACK = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_return = 22,
  anon_sym_COLON_COLON = 23,
  sym_string = 24,
  anon_sym_POUNDimp = 25,
  anon_sym_LT = 26,
  anon_sym_GT = 27,
  anon_sym_POUNDextern = 28,
  sym_identifier = 29,
  sym_number = 30,
  sym_decl_const = 31,
  sym_comment = 32,
  sym_source_file = 33,
  sym__definition = 34,
  sym_function_definition = 35,
  sym_parameter_list_defn = 36,
  sym_parameter_defn = 37,
  sym_parameter_list = 38,
  sym__type = 39,
  sym_primitive_type = 40,
  sym_slice_type = 41,
  sym_scope = 42,
  sym__statement = 43,
  sym_return_statement = 44,
  sym_function_call = 45,
  sym__expression = 46,
  sym_pkg = 47,
  sym__preproc = 48,
  sym_preproc_import = 49,
  sym_preproc_extern = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_parameter_list_defn_repeat1 = 52,
  aux_sym_parameter_list_repeat1 = 53,
  aux_sym_scope_repeat1 = 54,
  aux_sym_pkg_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_raw] = "raw",
  [anon_sym_str] = "str",
  [anon_sym_i8] = "i8",
  [anon_sym_i16] = "i16",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_u32] = "u32",
  [anon_sym_u64] = "u64",
  [anon_sym_f16] = "f16",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_return] = "return",
  [anon_sym_COLON_COLON] = "::",
  [sym_string] = "string",
  [anon_sym_POUNDimp] = "#imp",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_POUNDextern] = "#extern",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_decl_const] = "decl_const",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list_defn] = "parameter_list_defn",
  [sym_parameter_defn] = "parameter_defn",
  [sym_parameter_list] = "parameter_list",
  [sym__type] = "_type",
  [sym_primitive_type] = "primitive_type",
  [sym_slice_type] = "slice_type",
  [sym_scope] = "scope",
  [sym__statement] = "_statement",
  [sym_return_statement] = "return_statement",
  [sym_function_call] = "function_call",
  [sym__expression] = "_expression",
  [sym_pkg] = "pkg",
  [sym__preproc] = "_preproc",
  [sym_preproc_import] = "preproc_import",
  [sym_preproc_extern] = "preproc_extern",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_defn_repeat1] = "parameter_list_defn_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_scope_repeat1] = "scope_repeat1",
  [aux_sym_pkg_repeat1] = "pkg_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_raw] = anon_sym_raw,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_f16] = anon_sym_f16,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_string] = sym_string,
  [anon_sym_POUNDimp] = anon_sym_POUNDimp,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_POUNDextern] = anon_sym_POUNDextern,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_decl_const] = sym_decl_const,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list_defn] = sym_parameter_list_defn,
  [sym_parameter_defn] = sym_parameter_defn,
  [sym_parameter_list] = sym_parameter_list,
  [sym__type] = sym__type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_slice_type] = sym_slice_type,
  [sym_scope] = sym_scope,
  [sym__statement] = sym__statement,
  [sym_return_statement] = sym_return_statement,
  [sym_function_call] = sym_function_call,
  [sym__expression] = sym__expression,
  [sym_pkg] = sym_pkg,
  [sym__preproc] = sym__preproc,
  [sym_preproc_import] = sym_preproc_import,
  [sym_preproc_extern] = sym_preproc_extern,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_defn_repeat1] = aux_sym_parameter_list_defn_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_scope_repeat1] = aux_sym_scope_repeat1,
  [aux_sym_pkg_repeat1] = aux_sym_pkg_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_raw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDimp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDextern] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_const] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_slice_type] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_pkg] = {
    .visible = true,
    .named = true,
  },
  [sym__preproc] = {
    .visible = false,
    .named = true,
  },
  [sym_preproc_import] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_extern] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_defn_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scope_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pkg_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 3,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 14,
  [22] = 22,
  [23] = 23,
  [24] = 13,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 23,
  [31] = 31,
  [32] = 22,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 38,
  [53] = 53,
  [54] = 54,
  [55] = 46,
  [56] = 50,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 57,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 59,
  [73] = 69,
  [74] = 74,
  [75] = 62,
  [76] = 65,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '"', 1,
        '#', 23,
        '(', 42,
        ')', 44,
        ',', 43,
        '/', 3,
        ':', 46,
        '<', 68,
        '>', 70,
        '[', 21,
        'f', 7,
        'i', 8,
        'r', 22,
        's', 32,
        'u', 9,
        '{', 61,
        '}', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(38);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(45);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(72);
      if (lookahead == '}') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(81);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(80);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(4);
      END_STATE();
    case 7:
      if (lookahead == '1') ADVANCE(16);
      if (lookahead == '3') ADVANCE(10);
      if (lookahead == '6') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == '1') ADVANCE(17);
      if (lookahead == '3') ADVANCE(11);
      if (lookahead == '6') ADVANCE(14);
      if (lookahead == '8') ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == '1') ADVANCE(18);
      if (lookahead == '3') ADVANCE(12);
      if (lookahead == '6') ADVANCE(15);
      if (lookahead == '8') ADVANCE(53);
      END_STATE();
    case 10:
      if (lookahead == '2') ADVANCE(58);
      END_STATE();
    case 11:
      if (lookahead == '2') ADVANCE(51);
      END_STATE();
    case 12:
      if (lookahead == '2') ADVANCE(55);
      END_STATE();
    case 13:
      if (lookahead == '4') ADVANCE(59);
      END_STATE();
    case 14:
      if (lookahead == '4') ADVANCE(52);
      END_STATE();
    case 15:
      if (lookahead == '4') ADVANCE(56);
      END_STATE();
    case 16:
      if (lookahead == '6') ADVANCE(57);
      END_STATE();
    case 17:
      if (lookahead == '6') ADVANCE(50);
      END_STATE();
    case 18:
      if (lookahead == '6') ADVANCE(54);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '~') ADVANCE(79);
      END_STATE();
    case 20:
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 21:
      if (lookahead == ']') ADVANCE(60);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(36);
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(37);
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(63);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(71);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(67);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 36:
      if (lookahead == 'w') ADVANCE(47);
      END_STATE();
    case 37:
      if (lookahead == 'x') ADVANCE(34);
      END_STATE();
    case 38:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '"', 1,
        '#', 23,
        '(', 42,
        ')', 44,
        ',', 43,
        '/', 3,
        ':', 19,
        '>', 69,
        '{', 61,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '~') ADVANCE(79);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_raw);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_i16);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_f16);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_return);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_POUNDimp);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_POUNDextern);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(75);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(64);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(73);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(76);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(74);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_decl_const);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(81);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 39},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 39},
  [12] = {.lex_state = 39},
  [13] = {.lex_state = 39},
  [14] = {.lex_state = 39},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 39},
  [26] = {.lex_state = 39},
  [27] = {.lex_state = 39},
  [28] = {.lex_state = 39},
  [29] = {.lex_state = 39},
  [30] = {.lex_state = 39},
  [31] = {.lex_state = 39},
  [32] = {.lex_state = 39},
  [33] = {.lex_state = 39},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 39},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 39},
  [38] = {.lex_state = 39},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 39},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 39},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 39},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 39},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 39},
  [55] = {.lex_state = 39},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 39},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 39},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 39},
  [63] = {.lex_state = 39},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 39},
  [66] = {.lex_state = 39},
  [67] = {.lex_state = 39},
  [68] = {.lex_state = 39},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 39},
  [76] = {.lex_state = 39},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_raw] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_f16] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_POUNDimp] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_POUNDextern] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_decl_const] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(70),
    [sym__definition] = STATE(11),
    [sym_function_definition] = STATE(11),
    [sym__preproc] = STATE(11),
    [sym_preproc_import] = STATE(11),
    [sym_preproc_extern] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUNDimp] = ACTIONS(7),
    [anon_sym_POUNDextern] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(45), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(13), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [27] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(30), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(13), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [54] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(48), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(13), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [81] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(13), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(13), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [108] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(23), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(17), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [135] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(24), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(17), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [162] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_POUNDimp,
    ACTIONS(27), 1,
      anon_sym_POUNDextern,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(67), 1,
      sym_pkg,
    STATE(9), 7,
      sym__statement,
      sym_return_statement,
      sym_function_call,
      sym__preproc,
      sym_preproc_import,
      sym_preproc_extern,
      aux_sym_scope_repeat1,
  [193] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_POUNDimp,
    ACTIONS(27), 1,
      anon_sym_POUNDextern,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      sym_pkg,
    STATE(10), 7,
      sym__statement,
      sym_return_statement,
      sym_function_call,
      sym__preproc,
      sym_preproc_import,
      sym_preproc_extern,
      aux_sym_scope_repeat1,
  [224] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      anon_sym_return,
    ACTIONS(38), 1,
      anon_sym_POUNDimp,
    ACTIONS(41), 1,
      anon_sym_POUNDextern,
    ACTIONS(44), 1,
      sym_identifier,
    STATE(67), 1,
      sym_pkg,
    STATE(10), 7,
      sym__statement,
      sym_return_statement,
      sym_function_call,
      sym__preproc,
      sym_preproc_import,
      sym_preproc_extern,
      aux_sym_scope_repeat1,
  [255] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_POUNDimp,
    ACTIONS(9), 1,
      anon_sym_POUNDextern,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(12), 6,
      sym__definition,
      sym_function_definition,
      sym__preproc,
      sym_preproc_import,
      sym_preproc_extern,
      aux_sym_source_file_repeat1,
  [279] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_POUNDimp,
    ACTIONS(54), 1,
      anon_sym_POUNDextern,
    ACTIONS(57), 1,
      sym_identifier,
    STATE(12), 6,
      sym__definition,
      sym_function_definition,
      sym__preproc,
      sym_preproc_import,
      sym_preproc_extern,
      aux_sym_source_file_repeat1,
  [303] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      sym_identifier,
  [316] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      sym_identifier,
  [329] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 2,
      anon_sym_return,
      sym_identifier,
    ACTIONS(64), 3,
      anon_sym_RBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
  [342] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 2,
      anon_sym_return,
      sym_identifier,
    ACTIONS(68), 3,
      anon_sym_RBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
  [355] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      anon_sym_return,
      sym_identifier,
    ACTIONS(72), 3,
      anon_sym_RBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
  [368] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 2,
      anon_sym_return,
      sym_identifier,
    ACTIONS(76), 3,
      anon_sym_RBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
  [381] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 2,
      anon_sym_return,
      sym_identifier,
    ACTIONS(80), 3,
      anon_sym_RBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
  [394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 2,
      anon_sym_return,
      sym_identifier,
    ACTIONS(84), 3,
      anon_sym_RBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
  [407] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 2,
      anon_sym_return,
      sym_identifier,
    ACTIONS(62), 3,
      anon_sym_RBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
  [420] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 2,
      anon_sym_return,
      sym_identifier,
    ACTIONS(90), 3,
      anon_sym_RBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
  [433] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 2,
      anon_sym_return,
      sym_identifier,
    ACTIONS(94), 3,
      anon_sym_RBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
  [446] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 2,
      anon_sym_return,
      sym_identifier,
    ACTIONS(60), 3,
      anon_sym_RBRACE,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
  [459] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym__expression,
    ACTIONS(102), 3,
      sym_string,
      sym_identifier,
      sym_number,
  [474] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(15), 1,
      sym__expression,
    ACTIONS(104), 3,
      sym_string,
      sym_identifier,
      sym_number,
  [486] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_LPAREN,
    ACTIONS(108), 1,
      anon_sym_COLON_COLON,
    STATE(17), 1,
      sym_parameter_list,
    STATE(52), 1,
      aux_sym_pkg_repeat1,
  [502] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      sym_identifier,
  [512] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      sym_identifier,
  [522] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      sym_identifier,
  [532] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      sym_identifier,
  [542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      sym_identifier,
  [552] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(53), 1,
      sym__expression,
    ACTIONS(116), 3,
      sym_string,
      sym_identifier,
      sym_number,
  [564] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_parameter_list_defn_repeat1,
  [577] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_GT,
    ACTIONS(123), 1,
      anon_sym_COLON_COLON,
    STATE(38), 1,
      aux_sym_pkg_repeat1,
  [590] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_parameter_list_defn_repeat1,
  [603] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(131), 1,
      sym_identifier,
    STATE(41), 1,
      sym_parameter_defn,
  [616] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_COLON_COLON,
    ACTIONS(133), 1,
      anon_sym_GT,
    STATE(43), 1,
      aux_sym_pkg_repeat1,
  [629] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_parameter_list_repeat1,
  [642] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_parameter_list_repeat1,
  [655] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_COMMA,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      aux_sym_parameter_list_defn_repeat1,
  [668] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_parameter_list_repeat1,
  [681] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_COLON_COLON,
    ACTIONS(151), 1,
      anon_sym_GT,
    STATE(43), 1,
      aux_sym_pkg_repeat1,
  [694] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [702] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_scope,
  [712] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(68), 1,
      sym_pkg,
  [722] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    STATE(58), 1,
      sym_parameter_list_defn,
  [732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [740] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym_identifier,
    STATE(44), 1,
      sym_parameter_defn,
  [750] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    STATE(59), 1,
      sym_parameter_list_defn,
  [760] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_parameter_list,
  [770] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_COLON_COLON,
    STATE(43), 1,
      aux_sym_pkg_repeat1,
  [780] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [788] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 2,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [796] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(57), 1,
      sym_pkg,
  [806] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_parameter_list_defn,
  [816] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_GT,
  [823] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_GT_GT,
  [830] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_GT_GT,
  [837] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_identifier,
  [844] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_GT_GT,
  [851] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_decl_const,
  [858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_identifier,
  [865] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_COLON,
  [872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_identifier,
  [879] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym_decl_const,
  [886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COLON_COLON,
  [893] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_GT,
  [900] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_LT,
  [907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
  [914] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_GT_GT,
  [921] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_GT_GT,
  [928] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_LT,
  [935] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_GT_GT,
  [942] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_decl_const,
  [949] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 135,
  [SMALL_STATE(8)] = 162,
  [SMALL_STATE(9)] = 193,
  [SMALL_STATE(10)] = 224,
  [SMALL_STATE(11)] = 255,
  [SMALL_STATE(12)] = 279,
  [SMALL_STATE(13)] = 303,
  [SMALL_STATE(14)] = 316,
  [SMALL_STATE(15)] = 329,
  [SMALL_STATE(16)] = 342,
  [SMALL_STATE(17)] = 355,
  [SMALL_STATE(18)] = 368,
  [SMALL_STATE(19)] = 381,
  [SMALL_STATE(20)] = 394,
  [SMALL_STATE(21)] = 407,
  [SMALL_STATE(22)] = 420,
  [SMALL_STATE(23)] = 433,
  [SMALL_STATE(24)] = 446,
  [SMALL_STATE(25)] = 459,
  [SMALL_STATE(26)] = 474,
  [SMALL_STATE(27)] = 486,
  [SMALL_STATE(28)] = 502,
  [SMALL_STATE(29)] = 512,
  [SMALL_STATE(30)] = 522,
  [SMALL_STATE(31)] = 532,
  [SMALL_STATE(32)] = 542,
  [SMALL_STATE(33)] = 552,
  [SMALL_STATE(34)] = 564,
  [SMALL_STATE(35)] = 577,
  [SMALL_STATE(36)] = 590,
  [SMALL_STATE(37)] = 603,
  [SMALL_STATE(38)] = 616,
  [SMALL_STATE(39)] = 629,
  [SMALL_STATE(40)] = 642,
  [SMALL_STATE(41)] = 655,
  [SMALL_STATE(42)] = 668,
  [SMALL_STATE(43)] = 681,
  [SMALL_STATE(44)] = 694,
  [SMALL_STATE(45)] = 702,
  [SMALL_STATE(46)] = 712,
  [SMALL_STATE(47)] = 722,
  [SMALL_STATE(48)] = 732,
  [SMALL_STATE(49)] = 740,
  [SMALL_STATE(50)] = 750,
  [SMALL_STATE(51)] = 760,
  [SMALL_STATE(52)] = 770,
  [SMALL_STATE(53)] = 780,
  [SMALL_STATE(54)] = 788,
  [SMALL_STATE(55)] = 796,
  [SMALL_STATE(56)] = 806,
  [SMALL_STATE(57)] = 816,
  [SMALL_STATE(58)] = 823,
  [SMALL_STATE(59)] = 830,
  [SMALL_STATE(60)] = 837,
  [SMALL_STATE(61)] = 844,
  [SMALL_STATE(62)] = 851,
  [SMALL_STATE(63)] = 858,
  [SMALL_STATE(64)] = 865,
  [SMALL_STATE(65)] = 872,
  [SMALL_STATE(66)] = 879,
  [SMALL_STATE(67)] = 886,
  [SMALL_STATE(68)] = 893,
  [SMALL_STATE(69)] = 900,
  [SMALL_STATE(70)] = 907,
  [SMALL_STATE(71)] = 914,
  [SMALL_STATE(72)] = 921,
  [SMALL_STATE(73)] = 928,
  [SMALL_STATE(74)] = 935,
  [SMALL_STATE(75)] = 942,
  [SMALL_STATE(76)] = 949,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice_type, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_import, 4, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_import, 4, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_extern, 6, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_extern, 6, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slice_type, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pkg, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_defn_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_defn_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pkg, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pkg_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pkg_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_defn, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list_defn, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [187] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list_defn, 4, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list_defn, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_caz(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "caz",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
