/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 143
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 73
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_GT_GT = 2,
  anon_sym_LPAREN = 3,
  anon_sym_COMMA = 4,
  anon_sym_RPAREN = 5,
  anon_sym_raw = 6,
  anon_sym_str = 7,
  anon_sym_i8 = 8,
  anon_sym_i16 = 9,
  anon_sym_i32 = 10,
  anon_sym_i64 = 11,
  anon_sym_u8 = 12,
  anon_sym_u16 = 13,
  anon_sym_u32 = 14,
  anon_sym_u64 = 15,
  anon_sym_f16 = 16,
  anon_sym_f32 = 17,
  anon_sym_f64 = 18,
  anon_sym_LBRACK_RBRACK = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_struct = 22,
  anon_sym_LT_LT = 23,
  anon_sym_ret = 24,
  anon_sym_COLON_COLON = 25,
  sym_string = 26,
  sym_back_dir = 27,
  anon_sym_POUNDlib = 28,
  anon_sym_LT = 29,
  anon_sym_GT = 30,
  anon_sym_POUNDimp = 31,
  anon_sym_as = 32,
  anon_sym_POUNDextern = 33,
  anon_sym_POUNDuse = 34,
  anon_sym_POUNDload = 35,
  sym_identifier = 36,
  sym_number = 37,
  sym_decl_const = 38,
  sym_decl_mut = 39,
  sym_comment = 40,
  sym_source_file = 41,
  sym__definition = 42,
  sym_function_definition = 43,
  sym_parameter_list_defn = 44,
  sym_parameter_defn = 45,
  sym_parameter_list = 46,
  sym__type = 47,
  sym_primitive_type = 48,
  sym_slice_type = 49,
  sym_scope = 50,
  sym_struct = 51,
  sym_struct_scope = 52,
  sym_var_decl = 53,
  sym__statement = 54,
  sym_return_statement = 55,
  sym_function_call = 56,
  sym__expression = 57,
  sym_pkg = 58,
  sym__preproc = 59,
  sym_preproc_library = 60,
  sym_preproc_import = 61,
  sym_preproc_extern = 62,
  sym_preproc_use = 63,
  sym_preproc_load = 64,
  aux_sym_source_file_repeat1 = 65,
  aux_sym_parameter_list_defn_repeat1 = 66,
  aux_sym_parameter_list_repeat1 = 67,
  aux_sym_scope_repeat1 = 68,
  aux_sym_struct_repeat1 = 69,
  aux_sym_struct_scope_repeat1 = 70,
  aux_sym_function_call_repeat1 = 71,
  aux_sym_pkg_repeat1 = 72,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_raw] = "raw",
  [anon_sym_str] = "str",
  [anon_sym_i8] = "i8",
  [anon_sym_i16] = "i16",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_u32] = "u32",
  [anon_sym_u64] = "u64",
  [anon_sym_f16] = "f16",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_struct] = "struct",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_ret] = "ret",
  [anon_sym_COLON_COLON] = "::",
  [sym_string] = "string",
  [sym_back_dir] = "back_dir",
  [anon_sym_POUNDlib] = "#lib",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_POUNDimp] = "#imp",
  [anon_sym_as] = "as",
  [anon_sym_POUNDextern] = "#extern",
  [anon_sym_POUNDuse] = "#use",
  [anon_sym_POUNDload] = "#load",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_decl_const] = "decl_const",
  [sym_decl_mut] = "decl_mut",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list_defn] = "parameter_list_defn",
  [sym_parameter_defn] = "parameter_defn",
  [sym_parameter_list] = "parameter_list",
  [sym__type] = "_type",
  [sym_primitive_type] = "primitive_type",
  [sym_slice_type] = "slice_type",
  [sym_scope] = "scope",
  [sym_struct] = "struct",
  [sym_struct_scope] = "struct_scope",
  [sym_var_decl] = "var_decl",
  [sym__statement] = "_statement",
  [sym_return_statement] = "return_statement",
  [sym_function_call] = "function_call",
  [sym__expression] = "_expression",
  [sym_pkg] = "pkg",
  [sym__preproc] = "_preproc",
  [sym_preproc_library] = "preproc_library",
  [sym_preproc_import] = "preproc_import",
  [sym_preproc_extern] = "preproc_extern",
  [sym_preproc_use] = "preproc_use",
  [sym_preproc_load] = "preproc_load",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_defn_repeat1] = "parameter_list_defn_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_scope_repeat1] = "scope_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_struct_scope_repeat1] = "struct_scope_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_pkg_repeat1] = "pkg_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_raw] = anon_sym_raw,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_f16] = anon_sym_f16,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_ret] = anon_sym_ret,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_string] = sym_string,
  [sym_back_dir] = sym_back_dir,
  [anon_sym_POUNDlib] = anon_sym_POUNDlib,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_POUNDimp] = anon_sym_POUNDimp,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_POUNDextern] = anon_sym_POUNDextern,
  [anon_sym_POUNDuse] = anon_sym_POUNDuse,
  [anon_sym_POUNDload] = anon_sym_POUNDload,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_decl_const] = sym_decl_const,
  [sym_decl_mut] = sym_decl_mut,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list_defn] = sym_parameter_list_defn,
  [sym_parameter_defn] = sym_parameter_defn,
  [sym_parameter_list] = sym_parameter_list,
  [sym__type] = sym__type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_slice_type] = sym_slice_type,
  [sym_scope] = sym_scope,
  [sym_struct] = sym_struct,
  [sym_struct_scope] = sym_struct_scope,
  [sym_var_decl] = sym_var_decl,
  [sym__statement] = sym__statement,
  [sym_return_statement] = sym_return_statement,
  [sym_function_call] = sym_function_call,
  [sym__expression] = sym__expression,
  [sym_pkg] = sym_pkg,
  [sym__preproc] = sym__preproc,
  [sym_preproc_library] = sym_preproc_library,
  [sym_preproc_import] = sym_preproc_import,
  [sym_preproc_extern] = sym_preproc_extern,
  [sym_preproc_use] = sym_preproc_use,
  [sym_preproc_load] = sym_preproc_load,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_defn_repeat1] = aux_sym_parameter_list_defn_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_scope_repeat1] = aux_sym_scope_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_struct_scope_repeat1] = aux_sym_struct_scope_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_pkg_repeat1] = aux_sym_pkg_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_raw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ret] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_back_dir] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDlib] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDimp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDextern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDuse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDload] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_const] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_mut] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_slice_type] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_var_decl] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_pkg] = {
    .visible = true,
    .named = true,
  },
  [sym__preproc] = {
    .visible = false,
    .named = true,
  },
  [sym_preproc_library] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_import] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_extern] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_use] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_load] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_defn_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scope_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_scope_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pkg_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 8,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 22,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 17,
  [35] = 35,
  [36] = 36,
  [37] = 16,
  [38] = 38,
  [39] = 39,
  [40] = 23,
  [41] = 41,
  [42] = 24,
  [43] = 28,
  [44] = 44,
  [45] = 35,
  [46] = 46,
  [47] = 33,
  [48] = 44,
  [49] = 36,
  [50] = 29,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 30,
  [55] = 41,
  [56] = 32,
  [57] = 57,
  [58] = 57,
  [59] = 59,
  [60] = 60,
  [61] = 59,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 66,
  [73] = 69,
  [74] = 74,
  [75] = 68,
  [76] = 70,
  [77] = 71,
  [78] = 67,
  [79] = 65,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 85,
  [92] = 80,
  [93] = 90,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 20,
  [102] = 21,
  [103] = 19,
  [104] = 104,
  [105] = 18,
  [106] = 106,
  [107] = 107,
  [108] = 38,
  [109] = 99,
  [110] = 97,
  [111] = 111,
  [112] = 112,
  [113] = 39,
  [114] = 114,
  [115] = 115,
  [116] = 100,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 120,
  [125] = 123,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 119,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 135,
  [138] = 127,
  [139] = 136,
  [140] = 140,
  [141] = 134,
  [142] = 128,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '"', 3,
        '#', 18,
        '(', 35,
        ')', 37,
        ',', 36,
        '.', 59,
        '/', 6,
        ':', 33,
        '<', 62,
        '=', 99,
        '>', 64,
        '[', 14,
        'a', 88,
        'f', 70,
        'i', 71,
        'r', 82,
        's', 89,
        'u', 72,
        '{', 52,
        '}', 53,
        '~', 98,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '.') ADVANCE(59);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(85);
      if (lookahead == 's') ADVANCE(92);
      if (lookahead == '}') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == ')') ADVANCE(37);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == 's') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '\\') ADVANCE(29);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '#', 18,
        ')', 37,
        ',', 36,
        '.', 59,
        '/', 6,
        ':', 11,
        '<', 61,
        '>', 13,
        'r', 85,
        '{', 52,
        '}', 53,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '.') ADVANCE(59);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == 'a') ADVANCE(88);
      if (lookahead == 'r') ADVANCE(85);
      if (lookahead == '}') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(101);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(100);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(7);
      END_STATE();
    case 10:
      ADVANCE_MAP(
        '/', 6,
        '=', 99,
        '[', 14,
        'f', 70,
        'i', 71,
        'r', 83,
        's', 89,
        'u', 72,
        '~', 98,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(57);
      END_STATE();
    case 12:
      if (lookahead == '<') ADVANCE(55);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == ']') ADVANCE(51);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'b') ADVANCE(60);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(21);
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(67);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(65);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 28:
      if (lookahead == 'x') ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 30:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '#', 18,
        ')', 37,
        ',', 36,
        '.', 59,
        '/', 6,
        ':', 11,
        '<', 12,
        '=', 99,
        '>', 63,
        '{', 52,
        '}', 53,
        '~', 98,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == 'a') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(57);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_raw);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_str);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_i8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_i16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_i32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_i64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_u8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_u16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_u32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_u64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_f16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_f32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_f64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_struct);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_ret);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_back_dir);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_POUNDlib);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(55);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(34);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_POUNDimp);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_POUNDextern);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_POUNDuse);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_POUNDload);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(79);
      if (lookahead == '3') ADVANCE(73);
      if (lookahead == '6') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '1', 80,
        '3', 74,
        '6', 77,
        '8', 40,
        '0', 96,
        '2', 96,
        '4', 96,
        '5', 96,
        '7', 96,
        '9', 96,
        '_', 96,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '1', 81,
        '3', 75,
        '6', 78,
        '8', 44,
        '0', 96,
        '2', 96,
        '4', 96,
        '5', 96,
        '7', 96,
        '9', 96,
        '_', 96,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(94);
      if (lookahead == 'e') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_decl_const);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_decl_mut);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(101);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 30},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 30},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 30},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 30},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 31},
  [43] = {.lex_state = 30},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 30},
  [46] = {.lex_state = 30},
  [47] = {.lex_state = 30},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 30},
  [50] = {.lex_state = 30},
  [51] = {.lex_state = 30},
  [52] = {.lex_state = 30},
  [53] = {.lex_state = 30},
  [54] = {.lex_state = 30},
  [55] = {.lex_state = 30},
  [56] = {.lex_state = 30},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 30},
  [63] = {.lex_state = 30},
  [64] = {.lex_state = 30},
  [65] = {.lex_state = 30},
  [66] = {.lex_state = 30},
  [67] = {.lex_state = 30},
  [68] = {.lex_state = 30},
  [69] = {.lex_state = 30},
  [70] = {.lex_state = 30},
  [71] = {.lex_state = 30},
  [72] = {.lex_state = 30},
  [73] = {.lex_state = 30},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 30},
  [76] = {.lex_state = 30},
  [77] = {.lex_state = 30},
  [78] = {.lex_state = 30},
  [79] = {.lex_state = 30},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 30},
  [85] = {.lex_state = 30},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 30},
  [88] = {.lex_state = 30},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 30},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 4},
  [95] = {.lex_state = 4},
  [96] = {.lex_state = 30},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 30},
  [102] = {.lex_state = 30},
  [103] = {.lex_state = 30},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 30},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 4},
  [108] = {.lex_state = 30},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 30},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 30},
  [114] = {.lex_state = 30},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 4},
  [118] = {.lex_state = 30},
  [119] = {.lex_state = 30},
  [120] = {.lex_state = 30},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 30},
  [124] = {.lex_state = 30},
  [125] = {.lex_state = 30},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 4},
  [128] = {.lex_state = 30},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 30},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 4},
  [136] = {.lex_state = 4},
  [137] = {.lex_state = 4},
  [138] = {.lex_state = 4},
  [139] = {.lex_state = 4},
  [140] = {.lex_state = 30},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 30},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_raw] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_f16] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_ret] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_back_dir] = ACTIONS(1),
    [anon_sym_POUNDlib] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_POUNDimp] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_POUNDextern] = ACTIONS(1),
    [anon_sym_POUNDuse] = ACTIONS(1),
    [anon_sym_POUNDload] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_decl_const] = ACTIONS(1),
    [sym_decl_mut] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(121),
    [sym__definition] = STATE(13),
    [sym_function_definition] = STATE(13),
    [sym__preproc] = STATE(13),
    [sym_preproc_library] = STATE(13),
    [sym_preproc_import] = STATE(13),
    [sym_preproc_extern] = STATE(13),
    [sym_preproc_use] = STATE(13),
    [sym_preproc_load] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUNDlib] = ACTIONS(7),
    [anon_sym_POUNDimp] = ACTIONS(9),
    [anon_sym_POUNDextern] = ACTIONS(11),
    [anon_sym_POUNDuse] = ACTIONS(13),
    [anon_sym_POUNDload] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_ret,
    ACTIONS(24), 1,
      sym_back_dir,
    ACTIONS(27), 1,
      anon_sym_POUNDlib,
    ACTIONS(30), 1,
      anon_sym_POUNDimp,
    ACTIONS(33), 1,
      anon_sym_POUNDextern,
    ACTIONS(36), 1,
      anon_sym_POUNDuse,
    ACTIONS(39), 1,
      anon_sym_POUNDload,
    ACTIONS(42), 1,
      sym_identifier,
    STATE(63), 1,
      aux_sym_function_call_repeat1,
    STATE(85), 1,
      aux_sym_pkg_repeat1,
    STATE(122), 1,
      sym_pkg,
    STATE(2), 11,
      sym_var_decl,
      sym__statement,
      sym_return_statement,
      sym_function_call,
      sym__preproc,
      sym_preproc_library,
      sym_preproc_import,
      sym_preproc_extern,
      sym_preproc_use,
      sym_preproc_load,
      aux_sym_scope_repeat1,
  [53] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    ACTIONS(47), 1,
      anon_sym_ret,
    ACTIONS(49), 1,
      sym_back_dir,
    ACTIONS(51), 1,
      anon_sym_POUNDlib,
    ACTIONS(53), 1,
      anon_sym_POUNDimp,
    ACTIONS(55), 1,
      anon_sym_POUNDextern,
    ACTIONS(57), 1,
      anon_sym_POUNDuse,
    ACTIONS(59), 1,
      anon_sym_POUNDload,
    ACTIONS(61), 1,
      sym_identifier,
    STATE(63), 1,
      aux_sym_function_call_repeat1,
    STATE(85), 1,
      aux_sym_pkg_repeat1,
    STATE(122), 1,
      sym_pkg,
    STATE(4), 11,
      sym_var_decl,
      sym__statement,
      sym_return_statement,
      sym_function_call,
      sym__preproc,
      sym_preproc_library,
      sym_preproc_import,
      sym_preproc_extern,
      sym_preproc_use,
      sym_preproc_load,
      aux_sym_scope_repeat1,
  [106] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_ret,
    ACTIONS(49), 1,
      sym_back_dir,
    ACTIONS(51), 1,
      anon_sym_POUNDlib,
    ACTIONS(53), 1,
      anon_sym_POUNDimp,
    ACTIONS(55), 1,
      anon_sym_POUNDextern,
    ACTIONS(57), 1,
      anon_sym_POUNDuse,
    ACTIONS(59), 1,
      anon_sym_POUNDload,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      aux_sym_function_call_repeat1,
    STATE(85), 1,
      aux_sym_pkg_repeat1,
    STATE(122), 1,
      sym_pkg,
    STATE(2), 11,
      sym_var_decl,
      sym__statement,
      sym_return_statement,
      sym_function_call,
      sym__preproc,
      sym_preproc_library,
      sym_preproc_import,
      sym_preproc_extern,
      sym_preproc_use,
      sym_preproc_load,
      aux_sym_scope_repeat1,
  [159] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 2,
      sym_decl_const,
      sym_decl_mut,
    STATE(100), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(65), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [193] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(75), 2,
      sym_decl_const,
      sym_decl_mut,
    STATE(116), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(65), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [227] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(77), 1,
      sym_identifier,
    STATE(106), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(65), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [257] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(79), 1,
      sym_identifier,
    STATE(49), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(65), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [287] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(81), 1,
      sym_identifier,
    STATE(16), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(65), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [317] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(83), 1,
      sym_identifier,
    STATE(112), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(65), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [347] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(89), 1,
      sym_identifier,
    STATE(37), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(85), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [377] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(91), 1,
      sym_identifier,
    STATE(36), 3,
      sym__type,
      sym_primitive_type,
      sym_slice_type,
    ACTIONS(85), 13,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
  [407] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_POUNDlib,
    ACTIONS(9), 1,
      anon_sym_POUNDimp,
    ACTIONS(11), 1,
      anon_sym_POUNDextern,
    ACTIONS(13), 1,
      anon_sym_POUNDuse,
    ACTIONS(15), 1,
      anon_sym_POUNDload,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    STATE(14), 9,
      sym__definition,
      sym_function_definition,
      sym__preproc,
      sym_preproc_library,
      sym_preproc_import,
      sym_preproc_extern,
      sym_preproc_use,
      sym_preproc_load,
      aux_sym_source_file_repeat1,
  [443] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      anon_sym_POUNDlib,
    ACTIONS(100), 1,
      anon_sym_POUNDimp,
    ACTIONS(103), 1,
      anon_sym_POUNDextern,
    ACTIONS(106), 1,
      anon_sym_POUNDuse,
    ACTIONS(109), 1,
      anon_sym_POUNDload,
    ACTIONS(112), 1,
      sym_identifier,
    STATE(14), 9,
      sym__definition,
      sym_function_definition,
      sym__preproc,
      sym_preproc_library,
      sym_preproc_import,
      sym_preproc_extern,
      sym_preproc_use,
      sym_preproc_load,
      aux_sym_source_file_repeat1,
  [479] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_struct,
    ACTIONS(119), 1,
      anon_sym_ret,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(121), 2,
      sym_string,
      sym_number,
    STATE(27), 2,
      sym_struct,
      sym__expression,
    ACTIONS(115), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [509] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 12,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
      sym_decl_const,
      sym_decl_mut,
  [527] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 12,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
      sym_decl_const,
      sym_decl_mut,
  [545] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(129), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [564] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(133), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [583] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(137), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [602] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(141), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [621] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COLON_COLON,
    ACTIONS(147), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(145), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [641] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COLON_COLON,
    ACTIONS(153), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(151), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [661] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_as,
    ACTIONS(157), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(155), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [681] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COLON_COLON,
    ACTIONS(145), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_GT,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [698] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(161), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [715] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(165), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [732] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(169), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [749] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(173), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [766] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(177), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [783] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(181), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [800] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(185), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [817] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(189), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(127), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [851] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(195), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [868] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(199), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [885] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(125), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [902] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(205), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [919] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(209), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [936] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COLON_COLON,
    ACTIONS(151), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_GT,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [953] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 2,
      anon_sym_ret,
      sym_identifier,
    ACTIONS(213), 7,
      anon_sym_RBRACE,
      sym_back_dir,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [970] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(217), 1,
      anon_sym_as,
    ACTIONS(155), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
  [988] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1001] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_struct,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(221), 2,
      sym_string,
      sym_number,
    STATE(92), 2,
      sym_struct,
      sym__expression,
  [1022] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1035] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1048] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1061] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_struct,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
    ACTIONS(231), 1,
      sym_identifier,
    ACTIONS(229), 2,
      sym_string,
      sym_number,
    STATE(80), 2,
      sym_struct,
      sym__expression,
  [1082] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1095] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1108] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1121] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1147] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1160] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1173] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDlib,
      anon_sym_POUNDimp,
      anon_sym_POUNDextern,
      anon_sym_POUNDuse,
      anon_sym_POUNDload,
      sym_identifier,
  [1186] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_struct,
    ACTIONS(241), 1,
      sym_identifier,
    ACTIONS(239), 2,
      sym_string,
      sym_number,
    STATE(39), 2,
      sym_struct,
      sym__expression,
  [1204] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_struct,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(245), 2,
      sym_string,
      sym_number,
    STATE(113), 2,
      sym_struct,
      sym__expression,
  [1222] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_struct,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(249), 2,
      sym_string,
      sym_number,
    STATE(108), 2,
      sym_struct,
      sym__expression,
  [1240] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_struct,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(253), 2,
      sym_string,
      sym_number,
    STATE(104), 2,
      sym_struct,
      sym__expression,
  [1258] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_struct,
    ACTIONS(259), 1,
      sym_identifier,
    ACTIONS(257), 2,
      sym_string,
      sym_number,
    STATE(38), 2,
      sym_struct,
      sym__expression,
  [1276] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym_back_dir,
    ACTIONS(264), 1,
      sym_identifier,
    STATE(62), 1,
      aux_sym_function_call_repeat1,
    STATE(85), 1,
      aux_sym_pkg_repeat1,
    STATE(122), 1,
      sym_pkg,
  [1295] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_back_dir,
    ACTIONS(267), 1,
      sym_identifier,
    STATE(62), 1,
      aux_sym_function_call_repeat1,
    STATE(85), 1,
      aux_sym_pkg_repeat1,
    STATE(122), 1,
      sym_pkg,
  [1314] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
    ACTIONS(271), 1,
      sym_identifier,
    STATE(64), 2,
      sym_var_decl,
      aux_sym_struct_scope_repeat1,
  [1328] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_back_dir,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_pkg_repeat1,
    STATE(125), 1,
      sym_pkg,
  [1344] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_back_dir,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_pkg_repeat1,
    STATE(120), 1,
      sym_pkg,
  [1360] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_RBRACE,
    ACTIONS(278), 1,
      sym_identifier,
    STATE(64), 2,
      sym_var_decl,
      aux_sym_struct_scope_repeat1,
  [1374] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
    ACTIONS(282), 1,
      anon_sym_LT_LT,
    STATE(20), 1,
      sym_struct_scope,
    STATE(71), 1,
      aux_sym_struct_repeat1,
  [1390] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_back_dir,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(43), 1,
      sym_pkg,
    STATE(85), 1,
      aux_sym_pkg_repeat1,
  [1406] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      sym_identifier,
    ACTIONS(284), 1,
      anon_sym_RBRACE,
    STATE(67), 2,
      sym_var_decl,
      aux_sym_struct_scope_repeat1,
  [1420] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
    ACTIONS(282), 1,
      anon_sym_LT_LT,
    STATE(19), 1,
      sym_struct_scope,
    STATE(87), 1,
      aux_sym_struct_repeat1,
  [1436] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_back_dir,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_pkg_repeat1,
    STATE(124), 1,
      sym_pkg,
  [1452] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_back_dir,
    ACTIONS(288), 1,
      sym_identifier,
    STATE(28), 1,
      sym_pkg,
    STATE(91), 1,
      aux_sym_pkg_repeat1,
  [1468] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COLON_COLON,
    ACTIONS(290), 1,
      anon_sym_COLON,
    ACTIONS(292), 1,
      anon_sym_LPAREN,
    STATE(31), 1,
      sym_parameter_list,
  [1484] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_LT_LT,
    ACTIONS(294), 1,
      anon_sym_LBRACE,
    STATE(77), 1,
      aux_sym_struct_repeat1,
    STATE(101), 1,
      sym_struct_scope,
  [1500] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      sym_identifier,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    STATE(78), 2,
      sym_var_decl,
      aux_sym_struct_scope_repeat1,
  [1514] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_LT_LT,
    ACTIONS(294), 1,
      anon_sym_LBRACE,
    STATE(87), 1,
      aux_sym_struct_repeat1,
    STATE(103), 1,
      sym_struct_scope,
  [1530] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      sym_identifier,
    ACTIONS(298), 1,
      anon_sym_RBRACE,
    STATE(64), 2,
      sym_var_decl,
      aux_sym_struct_scope_repeat1,
  [1544] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_back_dir,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_pkg_repeat1,
    STATE(123), 1,
      sym_pkg,
  [1560] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_parameter_list_repeat1,
  [1573] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_COMMA,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_parameter_list_defn_repeat1,
  [1586] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COLON_COLON,
    ACTIONS(292), 1,
      anon_sym_LPAREN,
    STATE(26), 1,
      sym_parameter_list,
  [1599] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_parameter_list_defn_repeat1,
  [1612] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      sym_back_dir,
    ACTIONS(316), 1,
      sym_identifier,
    STATE(84), 1,
      aux_sym_pkg_repeat1,
  [1625] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_back_dir,
    ACTIONS(321), 1,
      sym_identifier,
    STATE(84), 1,
      aux_sym_pkg_repeat1,
  [1638] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      anon_sym_COMMA,
    ACTIONS(323), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_parameter_list_defn_repeat1,
  [1651] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_LBRACE,
    ACTIONS(327), 1,
      anon_sym_LT_LT,
    STATE(87), 1,
      aux_sym_struct_repeat1,
  [1664] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      anon_sym_RPAREN,
    ACTIONS(332), 1,
      sym_identifier,
    STATE(86), 1,
      sym_parameter_defn,
  [1677] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_COMMA,
    ACTIONS(337), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_parameter_list_repeat1,
  [1690] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    ACTIONS(339), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_parameter_list_repeat1,
  [1703] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_back_dir,
    ACTIONS(341), 1,
      sym_identifier,
    STATE(84), 1,
      aux_sym_pkg_repeat1,
  [1716] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    ACTIONS(343), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_parameter_list_repeat1,
  [1729] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    ACTIONS(345), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_parameter_list_repeat1,
  [1742] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_GT_GT,
    ACTIONS(349), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_scope,
  [1755] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 2,
      anon_sym_GT_GT,
      anon_sym_LBRACE,
  [1763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 2,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
  [1771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_LPAREN,
    STATE(137), 1,
      sym_parameter_list_defn,
  [1781] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_LPAREN,
    STATE(94), 1,
      sym_parameter_list_defn,
  [1791] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_LPAREN,
    STATE(50), 1,
      sym_parameter_list,
  [1801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 2,
      sym_decl_const,
      sym_decl_mut,
  [1809] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1817] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1825] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1833] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1849] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_scope,
  [1859] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 2,
      anon_sym_GT_GT,
      anon_sym_LBRACE,
  [1867] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1875] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_LPAREN,
    STATE(29), 1,
      sym_parameter_list,
  [1885] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_LPAREN,
    STATE(135), 1,
      sym_parameter_list_defn,
  [1895] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 2,
      sym_back_dir,
      sym_identifier,
  [1903] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1911] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1919] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 2,
      sym_back_dir,
      sym_identifier,
  [1927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1935] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 2,
      sym_decl_const,
      sym_decl_mut,
  [1943] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 2,
      anon_sym_GT_GT,
      anon_sym_LBRACE,
  [1951] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym_identifier,
    STATE(115), 1,
      sym_parameter_defn,
  [1961] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      sym_identifier,
  [1968] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      anon_sym_GT,
  [1975] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      ts_builtin_sym_end,
  [1982] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 1,
      anon_sym_COLON_COLON,
  [1989] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 1,
      anon_sym_GT,
  [1996] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      anon_sym_GT,
  [2003] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 1,
      anon_sym_GT,
  [2010] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 1,
      sym_decl_const,
  [2017] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 1,
      anon_sym_LT,
  [2024] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 1,
      sym_identifier,
  [2031] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 1,
      anon_sym_COLON,
  [2038] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      anon_sym_COLON,
  [2045] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      anon_sym_COLON,
  [2052] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COLON_COLON,
  [2059] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      sym_identifier,
  [2066] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      sym_decl_const,
  [2073] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      anon_sym_GT_GT,
  [2080] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      anon_sym_LT,
  [2087] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      anon_sym_GT_GT,
  [2094] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      anon_sym_LT,
  [2101] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(409), 1,
      anon_sym_LT,
  [2108] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(411), 1,
      sym_identifier,
  [2115] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(413), 1,
      sym_decl_const,
  [2122] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(415), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 53,
  [SMALL_STATE(4)] = 106,
  [SMALL_STATE(5)] = 159,
  [SMALL_STATE(6)] = 193,
  [SMALL_STATE(7)] = 227,
  [SMALL_STATE(8)] = 257,
  [SMALL_STATE(9)] = 287,
  [SMALL_STATE(10)] = 317,
  [SMALL_STATE(11)] = 347,
  [SMALL_STATE(12)] = 377,
  [SMALL_STATE(13)] = 407,
  [SMALL_STATE(14)] = 443,
  [SMALL_STATE(15)] = 479,
  [SMALL_STATE(16)] = 509,
  [SMALL_STATE(17)] = 527,
  [SMALL_STATE(18)] = 545,
  [SMALL_STATE(19)] = 564,
  [SMALL_STATE(20)] = 583,
  [SMALL_STATE(21)] = 602,
  [SMALL_STATE(22)] = 621,
  [SMALL_STATE(23)] = 641,
  [SMALL_STATE(24)] = 661,
  [SMALL_STATE(25)] = 681,
  [SMALL_STATE(26)] = 698,
  [SMALL_STATE(27)] = 715,
  [SMALL_STATE(28)] = 732,
  [SMALL_STATE(29)] = 749,
  [SMALL_STATE(30)] = 766,
  [SMALL_STATE(31)] = 783,
  [SMALL_STATE(32)] = 800,
  [SMALL_STATE(33)] = 817,
  [SMALL_STATE(34)] = 834,
  [SMALL_STATE(35)] = 851,
  [SMALL_STATE(36)] = 868,
  [SMALL_STATE(37)] = 885,
  [SMALL_STATE(38)] = 902,
  [SMALL_STATE(39)] = 919,
  [SMALL_STATE(40)] = 936,
  [SMALL_STATE(41)] = 953,
  [SMALL_STATE(42)] = 970,
  [SMALL_STATE(43)] = 988,
  [SMALL_STATE(44)] = 1001,
  [SMALL_STATE(45)] = 1022,
  [SMALL_STATE(46)] = 1035,
  [SMALL_STATE(47)] = 1048,
  [SMALL_STATE(48)] = 1061,
  [SMALL_STATE(49)] = 1082,
  [SMALL_STATE(50)] = 1095,
  [SMALL_STATE(51)] = 1108,
  [SMALL_STATE(52)] = 1121,
  [SMALL_STATE(53)] = 1134,
  [SMALL_STATE(54)] = 1147,
  [SMALL_STATE(55)] = 1160,
  [SMALL_STATE(56)] = 1173,
  [SMALL_STATE(57)] = 1186,
  [SMALL_STATE(58)] = 1204,
  [SMALL_STATE(59)] = 1222,
  [SMALL_STATE(60)] = 1240,
  [SMALL_STATE(61)] = 1258,
  [SMALL_STATE(62)] = 1276,
  [SMALL_STATE(63)] = 1295,
  [SMALL_STATE(64)] = 1314,
  [SMALL_STATE(65)] = 1328,
  [SMALL_STATE(66)] = 1344,
  [SMALL_STATE(67)] = 1360,
  [SMALL_STATE(68)] = 1374,
  [SMALL_STATE(69)] = 1390,
  [SMALL_STATE(70)] = 1406,
  [SMALL_STATE(71)] = 1420,
  [SMALL_STATE(72)] = 1436,
  [SMALL_STATE(73)] = 1452,
  [SMALL_STATE(74)] = 1468,
  [SMALL_STATE(75)] = 1484,
  [SMALL_STATE(76)] = 1500,
  [SMALL_STATE(77)] = 1514,
  [SMALL_STATE(78)] = 1530,
  [SMALL_STATE(79)] = 1544,
  [SMALL_STATE(80)] = 1560,
  [SMALL_STATE(81)] = 1573,
  [SMALL_STATE(82)] = 1586,
  [SMALL_STATE(83)] = 1599,
  [SMALL_STATE(84)] = 1612,
  [SMALL_STATE(85)] = 1625,
  [SMALL_STATE(86)] = 1638,
  [SMALL_STATE(87)] = 1651,
  [SMALL_STATE(88)] = 1664,
  [SMALL_STATE(89)] = 1677,
  [SMALL_STATE(90)] = 1690,
  [SMALL_STATE(91)] = 1703,
  [SMALL_STATE(92)] = 1716,
  [SMALL_STATE(93)] = 1729,
  [SMALL_STATE(94)] = 1742,
  [SMALL_STATE(95)] = 1755,
  [SMALL_STATE(96)] = 1763,
  [SMALL_STATE(97)] = 1771,
  [SMALL_STATE(98)] = 1781,
  [SMALL_STATE(99)] = 1791,
  [SMALL_STATE(100)] = 1801,
  [SMALL_STATE(101)] = 1809,
  [SMALL_STATE(102)] = 1817,
  [SMALL_STATE(103)] = 1825,
  [SMALL_STATE(104)] = 1833,
  [SMALL_STATE(105)] = 1841,
  [SMALL_STATE(106)] = 1849,
  [SMALL_STATE(107)] = 1859,
  [SMALL_STATE(108)] = 1867,
  [SMALL_STATE(109)] = 1875,
  [SMALL_STATE(110)] = 1885,
  [SMALL_STATE(111)] = 1895,
  [SMALL_STATE(112)] = 1903,
  [SMALL_STATE(113)] = 1911,
  [SMALL_STATE(114)] = 1919,
  [SMALL_STATE(115)] = 1927,
  [SMALL_STATE(116)] = 1935,
  [SMALL_STATE(117)] = 1943,
  [SMALL_STATE(118)] = 1951,
  [SMALL_STATE(119)] = 1961,
  [SMALL_STATE(120)] = 1968,
  [SMALL_STATE(121)] = 1975,
  [SMALL_STATE(122)] = 1982,
  [SMALL_STATE(123)] = 1989,
  [SMALL_STATE(124)] = 1996,
  [SMALL_STATE(125)] = 2003,
  [SMALL_STATE(126)] = 2010,
  [SMALL_STATE(127)] = 2017,
  [SMALL_STATE(128)] = 2024,
  [SMALL_STATE(129)] = 2031,
  [SMALL_STATE(130)] = 2038,
  [SMALL_STATE(131)] = 2045,
  [SMALL_STATE(132)] = 2052,
  [SMALL_STATE(133)] = 2059,
  [SMALL_STATE(134)] = 2066,
  [SMALL_STATE(135)] = 2073,
  [SMALL_STATE(136)] = 2080,
  [SMALL_STATE(137)] = 2087,
  [SMALL_STATE(138)] = 2094,
  [SMALL_STATE(139)] = 2101,
  [SMALL_STATE(140)] = 2108,
  [SMALL_STATE(141)] = 2115,
  [SMALL_STATE(142)] = 2122,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(138),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(139),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(142),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(127),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(136),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(128),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(131),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice_type, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_scope, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_scope, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_scope, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_scope, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pkg, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pkg, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pkg, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pkg, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_import, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_import, 4, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_use, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_use, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_load, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_load, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_import, 6, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_import, 6, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_extern, 6, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_extern, 6, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slice_type, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decl, 4, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_decl, 4, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decl, 5, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_decl, 5, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_library, 4, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_library, 4, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [264] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_scope_repeat1, 2, 0, 0),
  [271] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [304] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_defn_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_defn_repeat1, 2, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [313] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pkg_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [316] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pkg_repeat1, 2, 0, 0), SHIFT_REPEAT(132),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [327] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(140),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [334] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list_defn, 2, 0, 0),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list_defn, 3, 0, 0),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pkg_repeat1, 2, 0, 0),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_defn, 3, 0, 0),
  [365] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list_defn, 4, 0, 0),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [375] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_caz(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "caz",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
